server:
  port: 9500

#logging:
#  level:
#     org.springframework.web: DEBUG
#  pattern:
#    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
 

     

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true  
  profiles:
    active:  path 
  application:
    name: api-gateway
# disable eureka by default

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
            